import React, { useState } from 'react'
import { userInfo } from '../../src/types'

// Cover Page can be generated by:
// - Profile picture's dominant colour 
// - Block hex code 
//  - Custom image 


function CoverPage(props: userInfo) {
  return (
    <div className={`${props.userInfo !== null ? ('bg-[#c1bdef] h-[328px]'):('h-[218px] bg-white') }  w-full transition duration`}></div>
  )
}

export default CoverPage