import { Layout } from '../components/layout'
import '../styles/globals.css'
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return <> <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="viewport" content="width=device-width,initial-scale=1" />
      {/* <meta name="viewport" content="viewport-fit=cover" /> */}
  </Head>
  <Layout>
    <Component {...pageProps} />
  </Layout>
  </>
}

export default MyApp
