import { height } from '@mui/system';
import React, { useState } from 'react'
import { userInfo } from '../../../src/types'
import ChangeCover from './ChangeCover'
import EditProfile from './EditProfile'

// Cover Page can be generated by:
// - Profile picture's dominant colour 
// - Block hex code 
//  - Custom image 




function CoverPage(props: userInfo) {
  const user_cover = props.userInfo.address_color;
  const coverStyle = { 
    backgroundColor: `${user_cover}`,
    height: 188
  }
  // console.log(user_cover)

  return (
    user_cover.length > 0 ? (
      <div style={coverStyle} className=" w-full transition duration relative">
        <div className='flex flex-row space-x-3 absolute right-1 bottom-1 pr-16 pb-3'>
          {/* <ChangeCover /> */}
          <EditProfile />
        </div>
        

      </div>
    ) : (
      <div className="h-[218px] bg-white w-full transition duration relative">
        <div className='flex flex-row space-x-3 absolute right-1 bottom-1 pr-16 pb-3'>
          {/* <ChangeCover /> */}
          <EditProfile />
        </div>

      </div>
    )
  
  )
}

export default CoverPage